import CheckBox from "@/component/checkbox";
import Guest from "@/component/guest";
import MovieItem from "@/component/Movie";
import NavigationBar from "@/component/navigation";
import styles from "@/styles/Home.module.css";
import { Button, FormControlLabel, TextField } from "@mui/material";
import Head from "next/head";
import { useState } from "react";
import movies from "../data/movie.json";

type visited = {
  name: string;
  liked: string[];
};
function GuestBook() {
  const [name, setName] = useState<string>("");
  const [like, setLike] = useState<string[]>([]);
  const [guestBooks, setGuestBooks] = useState<visited[]>([
    {
      name: "누누",
      liked: [
        "해리포터와 아즈카반의 죄수",
        "아바타2",
        "인셉션",
        "인터스텔라",
        "어벤져스 엔드게임",
      ],
    },
  ]);
  const onChangeName = (e: any) => {
    setName(e.target.value);
  };

  const onCheck = (movieName: string) => () => {
    setLike((prev) => prev.filter((data) => data !== movieName));
  };
  const onUndo = (movieName: string) => () => {
    const newOne = like.concat(movieName);
    newOne.sort();
    setLike(newOne);
  };
  const onSubmit = () => {
    if (name === "") {
      alert("이름을 입력해주세요");
      return;
    }
    setGuestBooks((prev) =>
      prev.concat({
        name: name,
        liked: like,
      })
    );
  };
  const onCancle = () => {
    setName("");
    setLike([]);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div style={{ marginTop: "100px" }}></div>
          <h1>방명록</h1>
          {guestBooks.map((guestBook) => (
            <Guest name={guestBook.name} liked={guestBook.liked}></Guest>
          ))}
          <div>
            <TextField
              id="outlined-controlled"
              value={name}
              onChange={onChangeName}
              placeholder="닉네임"
            ></TextField>
          </div>
          <div style={{ height: "40px", display: "flex" }}>
            {like.map((it) => (
              <MovieItem title={it}></MovieItem>
            ))}
          </div>

          {movies.items.map((movie) => (
            <FormControlLabel
              key={movie.title}
              control={
                <CheckBox
                  onCheck={onCheck(movie.title)}
                  onUndo={onUndo(movie.title)}
                />
              }
              label={movie.title}
            />
          ))}
          <Button variant="outlined" type="submit" onClick={onSubmit}>
            등록하기!
          </Button>
          <Button variant="outlined" type="reset" onClick={onCancle}>
            취소하기
          </Button>
          <NavigationBar />
        </div>
      </main>
    </>
  );
}

export default GuestBook;
