import CardCarousel from "@/component/cardcarousel";
import NavigationBar from "@/component/navigation";
import styles from "@/styles/Home.module.css";
import Head from "next/head";

function Movie() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              minHeight: "90vh",
              width: "100%",
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "center",
                paddingLeft: "10%",
                paddingRight: "10%",
              }}
            >
              <CardCarousel />
            </div>
          </div>
          <NavigationBar />
        </div>
      </main>
    </>
  );
}

export default Movie;
